# Generated by Django 6.0.3 on 2026-03-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
    ]
